// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/download.proto

package versions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Download struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VersionId            int32    `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	StorageType          string   `protobuf:"bytes,3,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"`
	Format               string   `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Protocol             string   `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Os                   string   `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	Arch                 string   `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"`
	Filename             string   `protobuf:"bytes,8,opt,name=filename,proto3" json:"filename,omitempty"`
	Extension            string   `protobuf:"bytes,9,opt,name=extension,proto3" json:"extension,omitempty"`
	ContentType          string   `protobuf:"bytes,10,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	TotalDownloads       int32    `protobuf:"varint,11,opt,name=total_downloads,json=totalDownloads,proto3" json:"total_downloads,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt            string   `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Data                 []byte   `protobuf:"bytes,14,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Download) Reset()         { *m = Download{} }
func (m *Download) String() string { return proto.CompactTextString(m) }
func (*Download) ProtoMessage()    {}
func (*Download) Descriptor() ([]byte, []int) {
	return fileDescriptor_download_a5d44dd49e21d1dd, []int{0}
}
func (m *Download) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Download.Unmarshal(m, b)
}
func (m *Download) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Download.Marshal(b, m, deterministic)
}
func (dst *Download) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Download.Merge(dst, src)
}
func (m *Download) XXX_Size() int {
	return xxx_messageInfo_Download.Size(m)
}
func (m *Download) XXX_DiscardUnknown() {
	xxx_messageInfo_Download.DiscardUnknown(m)
}

var xxx_messageInfo_Download proto.InternalMessageInfo

func (m *Download) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Download) GetVersionId() int32 {
	if m != nil {
		return m.VersionId
	}
	return 0
}

func (m *Download) GetStorageType() string {
	if m != nil {
		return m.StorageType
	}
	return ""
}

func (m *Download) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Download) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Download) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Download) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *Download) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Download) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *Download) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Download) GetTotalDownloads() int32 {
	if m != nil {
		return m.TotalDownloads
	}
	return 0
}

func (m *Download) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Download) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Download) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DownloadRequest struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DownloadId           int32     `protobuf:"varint,2,opt,name=download_id,json=downloadId,proto3" json:"download_id,omitempty"`
	Download             *Download `protobuf:"bytes,3,opt,name=download,proto3" json:"download,omitempty"`
	VersionId            string    `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Data                 []byte    `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Limit                int32     `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32     `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DownloadRequest) Reset()         { *m = DownloadRequest{} }
func (m *DownloadRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRequest) ProtoMessage()    {}
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_download_a5d44dd49e21d1dd, []int{1}
}
func (m *DownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRequest.Unmarshal(m, b)
}
func (m *DownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRequest.Marshal(b, m, deterministic)
}
func (dst *DownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRequest.Merge(dst, src)
}
func (m *DownloadRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadRequest.Size(m)
}
func (m *DownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRequest proto.InternalMessageInfo

func (m *DownloadRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DownloadRequest) GetDownloadId() int32 {
	if m != nil {
		return m.DownloadId
	}
	return 0
}

func (m *DownloadRequest) GetDownload() *Download {
	if m != nil {
		return m.Download
	}
	return nil
}

func (m *DownloadRequest) GetVersionId() string {
	if m != nil {
		return m.VersionId
	}
	return ""
}

func (m *DownloadRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DownloadRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DownloadRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type DownloadResponse struct {
	Download             *Download   `protobuf:"bytes,1,opt,name=download,proto3" json:"download,omitempty"`
	Downloads            []*Download `protobuf:"bytes,2,rep,name=downloads,proto3" json:"downloads,omitempty"`
	Limit                int32       `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32       `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DownloadResponse) Reset()         { *m = DownloadResponse{} }
func (m *DownloadResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadResponse) ProtoMessage()    {}
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_download_a5d44dd49e21d1dd, []int{2}
}
func (m *DownloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadResponse.Unmarshal(m, b)
}
func (m *DownloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadResponse.Marshal(b, m, deterministic)
}
func (dst *DownloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadResponse.Merge(dst, src)
}
func (m *DownloadResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadResponse.Size(m)
}
func (m *DownloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadResponse proto.InternalMessageInfo

func (m *DownloadResponse) GetDownload() *Download {
	if m != nil {
		return m.Download
	}
	return nil
}

func (m *DownloadResponse) GetDownloads() []*Download {
	if m != nil {
		return m.Downloads
	}
	return nil
}

func (m *DownloadResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DownloadResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func init() {
	proto.RegisterType((*Download)(nil), "versions.Download")
	proto.RegisterType((*DownloadRequest)(nil), "versions.DownloadRequest")
	proto.RegisterType((*DownloadResponse)(nil), "versions.DownloadResponse")
}

func init() { proto.RegisterFile("protos/download.proto", fileDescriptor_download_a5d44dd49e21d1dd) }

var fileDescriptor_download_a5d44dd49e21d1dd = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x95, 0xb4, 0x29, 0xc9, 0xb4, 0x74, 0x91, 0x05, 0xc8, 0x5a, 0x2d, 0xa2, 0xf4, 0x42,
	0x4f, 0x2d, 0x82, 0x27, 0x58, 0x89, 0xcb, 0x5e, 0x23, 0xee, 0x95, 0xa9, 0x9d, 0x12, 0x29, 0xf5,
	0x84, 0x78, 0x16, 0xd8, 0x77, 0xe0, 0x29, 0x78, 0x25, 0x5e, 0x08, 0x79, 0x6c, 0x37, 0xcb, 0x3f,
	0x69, 0x6f, 0xfe, 0xbe, 0xf1, 0xd8, 0x3f, 0xcf, 0x67, 0x78, 0xd6, 0x0f, 0x48, 0xe8, 0x76, 0x1a,
	0xbf, 0xda, 0x0e, 0x95, 0xde, 0xb2, 0x16, 0xe5, 0x17, 0x33, 0xb8, 0x16, 0xad, 0xbb, 0xbc, 0x3a,
	0x22, 0x1e, 0x3b, 0xb3, 0x53, 0x7d, 0xbb, 0x53, 0xd6, 0x22, 0x29, 0xf2, 0x7e, 0xd8, 0xb7, 0xfe,
	0x3e, 0x81, 0xf2, 0x7d, 0x6c, 0x15, 0x4b, 0xc8, 0x5b, 0x2d, 0xb3, 0x55, 0xb6, 0x29, 0xea, 0xbc,
	0xd5, 0xe2, 0x05, 0x40, 0x3c, 0x66, 0xdf, 0x6a, 0x99, 0xb3, 0x5f, 0x45, 0xe7, 0x46, 0x8b, 0x57,
	0xb0, 0x70, 0x84, 0x83, 0x3a, 0x9a, 0x3d, 0xdd, 0xf5, 0x46, 0x4e, 0x56, 0xd9, 0xa6, 0xaa, 0xe7,
	0xd1, 0xfb, 0x70, 0xd7, 0x1b, 0xf1, 0x1c, 0x66, 0x0d, 0x0e, 0x27, 0x45, 0x72, 0xca, 0xc5, 0xa8,
	0xc4, 0x25, 0x94, 0x7c, 0xff, 0x01, 0x3b, 0x59, 0x70, 0xe5, 0xac, 0x3d, 0x05, 0x3a, 0x39, 0x63,
	0x37, 0x47, 0x27, 0x04, 0x4c, 0xd5, 0x70, 0xf8, 0x24, 0x1f, 0xb1, 0xc3, 0x6b, 0xdf, 0xdf, 0xb4,
	0x9d, 0xb1, 0xea, 0x64, 0x64, 0x19, 0xfa, 0x93, 0x16, 0x57, 0x50, 0x99, 0x6f, 0x64, 0xac, 0xa7,
	0x94, 0x15, 0x17, 0x47, 0xc3, 0x43, 0x1f, 0xd0, 0x92, 0xb1, 0x14, 0xa0, 0x21, 0x40, 0x47, 0x8f,
	0xa1, 0x5f, 0xc3, 0x05, 0x21, 0xa9, 0x6e, 0x9f, 0x66, 0xea, 0xe4, 0x9c, 0xdf, 0xbe, 0x64, 0x3b,
	0x8d, 0xcb, 0xf9, 0xf9, 0xdc, 0xf6, 0x5a, 0x91, 0xd1, 0x7b, 0x45, 0x72, 0x11, 0xae, 0x8a, 0xce,
	0x35, 0xf9, 0xf2, 0x61, 0x30, 0xa9, 0xfc, 0x38, 0x94, 0xa3, 0x73, 0x4d, 0xfe, 0x5d, 0x5a, 0x91,
	0x92, 0xcb, 0x55, 0xb6, 0x59, 0xd4, 0xbc, 0x5e, 0xff, 0xcc, 0xe0, 0x22, 0x9d, 0x5f, 0x9b, 0xcf,
	0xb7, 0xc6, 0xd1, 0x5f, 0xa9, 0xbc, 0x84, 0x79, 0x02, 0x1b, 0x63, 0x81, 0x64, 0xdd, 0x68, 0xb1,
	0x85, 0x32, 0x29, 0xce, 0x64, 0xfe, 0x56, 0x6c, 0xd3, 0x77, 0xd8, 0x9e, 0x4f, 0x3f, 0xef, 0xf9,
	0x23, 0xe6, 0x10, 0xd4, 0xbd, 0x98, 0x13, 0x67, 0x31, 0x72, 0x8a, 0xa7, 0x50, 0x74, 0xed, 0xa9,
	0x25, 0x8e, 0xa9, 0xa8, 0x83, 0xf0, 0x69, 0x63, 0xd3, 0x38, 0x43, 0x9c, 0x55, 0x51, 0x47, 0xb5,
	0xfe, 0x91, 0xc1, 0x93, 0xf1, 0x55, 0xae, 0x47, 0xeb, 0xcc, 0x6f, 0x94, 0xd9, 0x03, 0x28, 0xdf,
	0x40, 0x35, 0xe6, 0x91, 0xaf, 0x26, 0xff, 0x69, 0x18, 0x37, 0x8d, 0x90, 0x93, 0x7f, 0x43, 0x4e,
	0xef, 0x43, 0x7e, 0x9c, 0xf1, 0x07, 0x7c, 0xf7, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xb2, 0x75,
	0x7c, 0x51, 0x03, 0x00, 0x00,
}
