// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/download.proto

package versions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Download struct {
	Link                 string   `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Format               string   `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Protocol             string   `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Os                   string   `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch                 string   `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Download) Reset()         { *m = Download{} }
func (m *Download) String() string { return proto.CompactTextString(m) }
func (*Download) ProtoMessage()    {}
func (*Download) Descriptor() ([]byte, []int) {
	return fileDescriptor_download_202d55d5e2353b18, []int{0}
}
func (m *Download) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Download.Unmarshal(m, b)
}
func (m *Download) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Download.Marshal(b, m, deterministic)
}
func (dst *Download) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Download.Merge(dst, src)
}
func (m *Download) XXX_Size() int {
	return xxx_messageInfo_Download.Size(m)
}
func (m *Download) XXX_DiscardUnknown() {
	xxx_messageInfo_Download.DiscardUnknown(m)
}

var xxx_messageInfo_Download proto.InternalMessageInfo

func (m *Download) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Download) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Download) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Download) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Download) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func init() {
	proto.RegisterType((*Download)(nil), "versions.Download")
}

func init() { proto.RegisterFile("protos/download.proto", fileDescriptor_download_202d55d5e2353b18) }

var fileDescriptor_download_202d55d5e2353b18 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8c, 0x31, 0x0e, 0x82, 0x40,
	0x10, 0x45, 0x03, 0x22, 0xc1, 0x29, 0x2c, 0x26, 0xd1, 0x6c, 0x88, 0x85, 0xb1, 0xb2, 0x92, 0xc2,
	0x2b, 0x78, 0x02, 0x6f, 0x30, 0x02, 0x22, 0x71, 0xdd, 0x4f, 0x76, 0x37, 0x78, 0x7d, 0xc3, 0x40,
	0xec, 0xfe, 0x7f, 0xf3, 0xe7, 0xd1, 0x6e, 0xf0, 0x88, 0x08, 0x55, 0x83, 0xaf, 0xb3, 0x90, 0xe6,
	0xa2, 0x9d, 0x8b, 0xb1, 0xf5, 0xa1, 0x87, 0x0b, 0xe5, 0xa1, 0x03, 0x3a, 0xdb, 0x56, 0x32, 0xf4,
	0x95, 0x38, 0x87, 0x28, 0x71, 0xe2, 0xf3, 0xee, 0x34, 0x52, 0x71, 0x5b, 0x3e, 0x99, 0x29, 0xb3,
	0xbd, 0x7b, 0x9b, 0xe4, 0x98, 0x9c, 0x37, 0x77, 0xcd, 0xbc, 0xa7, 0xfc, 0x09, 0xff, 0x91, 0x68,
	0x52, 0xa5, 0x4b, 0xe3, 0x92, 0x0a, 0x15, 0xd4, 0xb0, 0x66, 0xa5, 0x97, 0x7f, 0xe7, 0x2d, 0xa5,
	0x08, 0x26, 0x53, 0x9a, 0x22, 0x4c, 0x5e, 0xf1, 0xf5, 0xcb, 0xac, 0x67, 0xef, 0x94, 0x1f, 0xb9,
	0xae, 0xaf, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xef, 0xd4, 0x72, 0xbf, 0x00, 0x00, 0x00,
}
