// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/version.proto

package versions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VersionRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VersionId            int32    `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Version              *Version `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ApplicationId        string   `protobuf:"bytes,4,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Limit                int32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_version_6091351887285b62, []int{0}
}
func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (dst *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(dst, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

func (m *VersionRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VersionRequest) GetVersionId() int32 {
	if m != nil {
		return m.VersionId
	}
	return 0
}

func (m *VersionRequest) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *VersionRequest) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

func (m *VersionRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *VersionRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type VersionResponse struct {
	Version              *Version   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Versions             []*Version `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	Limit                int32      `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32      `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_version_6091351887285b62, []int{1}
}
func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (dst *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(dst, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *VersionResponse) GetVersions() []*Version {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *VersionResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *VersionResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Version struct {
	Id                   int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Major                string       `protobuf:"bytes,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor                string       `protobuf:"bytes,3,opt,name=minor,proto3" json:"minor,omitempty"`
	Revision             string       `protobuf:"bytes,4,opt,name=revision,proto3" json:"revision,omitempty"`
	Application          *Application `protobuf:"bytes,5,opt,name=application,proto3" json:"application,omitempty"`
	ApplicationId        string       `protobuf:"bytes,6,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Name                 string       `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Stable               bool         `protobuf:"varint,8,opt,name=stable,proto3" json:"stable,omitempty"`
	UpdatedAt            string       `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt            string       `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Downloads            []*Download  `protobuf:"bytes,11,rep,name=downloads,proto3" json:"downloads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_version_6091351887285b62, []int{2}
}
func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (dst *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(dst, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Version) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *Version) GetMinor() string {
	if m != nil {
		return m.Minor
	}
	return ""
}

func (m *Version) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *Version) GetApplication() *Application {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *Version) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

func (m *Version) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Version) GetStable() bool {
	if m != nil {
		return m.Stable
	}
	return false
}

func (m *Version) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Version) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Version) GetDownloads() []*Download {
	if m != nil {
		return m.Downloads
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionRequest)(nil), "versions.VersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "versions.VersionResponse")
	proto.RegisterType((*Version)(nil), "versions.Version")
}

func init() { proto.RegisterFile("protos/version.proto", fileDescriptor_version_6091351887285b62) }

var fileDescriptor_version_6091351887285b62 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4b, 0x6a, 0xeb, 0x30,
	0x14, 0x45, 0x4e, 0xec, 0xd8, 0xd7, 0xbc, 0x3c, 0x9e, 0x48, 0x1e, 0x22, 0xb4, 0x60, 0x02, 0x05,
	0x43, 0x69, 0x52, 0xd2, 0x41, 0xc7, 0x81, 0x4e, 0x32, 0xf5, 0xa0, 0xd3, 0xa0, 0x44, 0x4a, 0x50,
	0x71, 0x2c, 0xd7, 0x52, 0xd2, 0xc5, 0x74, 0x35, 0x5d, 0x48, 0xf7, 0x52, 0x2c, 0xcb, 0x9f, 0x52,
	0x43, 0x67, 0x3e, 0x1f, 0x5f, 0x9d, 0x7b, 0x24, 0x98, 0xe4, 0x85, 0xd4, 0x52, 0x2d, 0x2f, 0xbc,
	0x50, 0x42, 0x66, 0x0b, 0x03, 0xb1, 0x6f, 0xa1, 0x9a, 0x5d, 0x1d, 0xa5, 0x3c, 0xa6, 0x7c, 0x49,
	0x73, 0xb1, 0xa4, 0x59, 0x26, 0x35, 0xd5, 0x25, 0x5f, 0xf9, 0x66, 0xc4, 0xfe, 0x4d, 0xf3, 0x3c,
	0x15, 0x7b, 0x23, 0x59, 0x65, 0x6a, 0x15, 0x26, 0xdf, 0xb2, 0x54, 0x52, 0x56, 0xd1, 0xf3, 0x0f,
	0x04, 0xe3, 0xe7, 0x6a, 0x76, 0xc2, 0x5f, 0xcf, 0x5c, 0x69, 0x3c, 0x06, 0x47, 0x30, 0x82, 0x22,
	0x14, 0xbb, 0x89, 0x23, 0x18, 0xbe, 0x06, 0xb0, 0xa7, 0x6f, 0x05, 0x23, 0x8e, 0xe1, 0x03, 0xcb,
	0x6c, 0x18, 0xbe, 0x85, 0x91, 0x05, 0x64, 0x10, 0xa1, 0x38, 0x5c, 0xfd, 0x5b, 0xd4, 0x61, 0x17,
	0xf5, 0xe4, 0xda, 0x81, 0x6f, 0x60, 0xdc, 0x89, 0x56, 0xce, 0x1b, 0x46, 0x28, 0x0e, 0x92, 0x3f,
	0x1d, 0x76, 0xc3, 0xf0, 0x04, 0xdc, 0x54, 0x9c, 0x84, 0x26, 0xae, 0x39, 0xad, 0x02, 0xf8, 0x3f,
	0x78, 0xf2, 0x70, 0x50, 0x5c, 0x13, 0xcf, 0xd0, 0x16, 0xcd, 0xdf, 0x11, 0xfc, 0x6d, 0x76, 0x50,
	0xb9, 0xcc, 0x14, 0xef, 0xa6, 0x42, 0xbf, 0xa6, 0xba, 0x83, 0xa6, 0x5f, 0xe2, 0x44, 0x83, 0x7e,
	0x77, 0x63, 0x69, 0xd3, 0x0d, 0xfa, 0xd3, 0x0d, 0xbf, 0xa5, 0xfb, 0x74, 0x60, 0x64, 0x67, 0xfc,
	0xa8, 0x76, 0x02, 0xee, 0x89, 0xbe, 0xc8, 0xc2, 0xb4, 0x1a, 0x24, 0x15, 0x30, 0xac, 0xc8, 0x64,
	0x61, 0xe6, 0x97, 0x6c, 0x09, 0xf0, 0x0c, 0xfc, 0x82, 0x5f, 0x84, 0x59, 0xa9, 0x2a, 0xad, 0xc1,
	0xf8, 0x11, 0xc2, 0x4e, 0x81, 0xa6, 0xb5, 0x70, 0x35, 0x6d, 0x77, 0x58, 0xb7, 0x62, 0xd2, 0x75,
	0xf6, 0xdc, 0x87, 0xd7, 0x77, 0x1f, 0x18, 0x86, 0x19, 0x3d, 0x71, 0x32, 0x32, 0xa2, 0xf9, 0x2e,
	0xf7, 0x55, 0x9a, 0xee, 0x52, 0x4e, 0xfc, 0x08, 0xc5, 0x7e, 0x62, 0x51, 0xf9, 0x5c, 0xce, 0x39,
	0xa3, 0x9a, 0xb3, 0x2d, 0xd5, 0x24, 0x30, 0x7f, 0x04, 0x96, 0x59, 0xeb, 0x52, 0xde, 0x17, 0xbc,
	0x96, 0xa1, 0x92, 0x2d, 0xb3, 0xd6, 0xf8, 0x1e, 0x82, 0xfa, 0x85, 0x2a, 0x12, 0x9a, 0xbb, 0xc0,
	0xed, 0x1e, 0x4f, 0x56, 0x4a, 0x5a, 0xd3, 0xce, 0x33, 0x0f, 0xf9, 0xe1, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0x30, 0x01, 0x86, 0xe1, 0x39, 0x03, 0x00, 0x00,
}
